logging:
  level:
    root: info
    web: info
    sql: debug
    feign: info
    com.zaxxer.hikari: trace
    com.zaxxer.hikari.HikariConfig: DEBUG
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,${app.default.timezone}

spring:
  profiles:
    active:
      - h2
      - flyway
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  datasource:
    hikari:
      auto-commit: false
  flyway:
    enabled: false
  liquibase:
    enabled: false
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
        session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 20
        jdbc:
          batch_size: ${app.datasource.batch_size}
          time_zone: ${app.default.timezone}
        order:
          inserts: true
          updates: true
        connection.provider_disables_autocommit: true
        id.optimizer.pooled.preferred: pooled-lo
  h2:
    console:
      enabled: false
  application:
    name: shoppinglist
  jackson: #these properties are overridden in case we configure @EnableWebMvc,in that case we need to implement custom MappingJackson2HttpMessageConverter
    default-property-inclusion: non-null
    mapper:
      default-view-inclusion: true
    deserialization:
      fail-on-unknown-properties: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
server:
  shutdown: graceful
  port: 8080
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 2KB

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    java:
      enabled: true

app:
  default:
    #    timezone: IST
    timezone: UTC
  datasource:
    batch_size: 500

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
  cache:
    disabled: true

---
spring:
  config:
    activate:
      on-profile:
        - h2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    #    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
---
spring:
  config:
    activate:
      on-profile:
        - flyway
  flyway:
    enabled: true
    baseline-on-migrate: true
  liquibase:
    enabled: false
---
spring:
  config:
    activate:
      on-profile:
        - test
  datasource:
#    url: jdbc:tc:mysql:latest:///testdb
#    url: jdbc:tc:sqlserver:latest:///testdb
#    url: jdbc:tc:postgresql:latest:///testdb
#    url: jdbc:tc:oracle:latest:///testdb
#    url: jdbc:tc:mariadb:latest:///testdb
#    url: jdbc:tc:cockroach:latest:///testdb
#    url: jdbc:tc:db2:latest:///testdb
---
spring:
  config:
    activate:
      on-profile:
        - liquibase
  flyway:
    enabled: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/2022/01/15-01-changelog.xml
    parameters:
      sequenceBatch: ${app.datasource.batch_size}
---
spring:
  config:
    activate:
      on-profile:
        - postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/amigoscode
    username: amigoscode
    password: password
---